package Vista;

import java.awt.Color;

/**
 *
 * @author usuario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarElector = new javax.swing.JButton();
        btnImportarDatosDeArchivo = new javax.swing.JButton();
        btnPadronElectoral = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCrearListaCandidato = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre de Actividad", "Articulo", "Fecha inicio", "Duracion", "Fecha fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestion de Electores");

        btnRegistrarElector.setBackground(new java.awt.Color(204, 204, 255));
        btnRegistrarElector.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarElector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Nuevo Elector.png"))); // NOI18N
        btnRegistrarElector.setText("Registrar Elector");
        btnRegistrarElector.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarElector.setBorderPainted(false);
        btnRegistrarElector.setContentAreaFilled(false);
        btnRegistrarElector.setFocusable(false);
        btnRegistrarElector.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarElector.setIconTextGap(8);
        btnRegistrarElector.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarElector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarElectorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarElectorMouseExited(evt);
            }
        });

        btnImportarDatosDeArchivo.setBackground(new java.awt.Color(204, 204, 255));
        btnImportarDatosDeArchivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImportarDatosDeArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Importar.png"))); // NOI18N
        btnImportarDatosDeArchivo.setText("Importar Electores");
        btnImportarDatosDeArchivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnImportarDatosDeArchivo.setBorderPainted(false);
        btnImportarDatosDeArchivo.setContentAreaFilled(false);
        btnImportarDatosDeArchivo.setFocusable(false);
        btnImportarDatosDeArchivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImportarDatosDeArchivo.setIconTextGap(8);
        btnImportarDatosDeArchivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImportarDatosDeArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImportarDatosDeArchivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnImportarDatosDeArchivoMouseExited(evt);
            }
        });

        btnPadronElectoral.setBackground(new java.awt.Color(204, 204, 255));
        btnPadronElectoral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPadronElectoral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Lista.png"))); // NOI18N
        btnPadronElectoral.setText("Padron Electoral");
        btnPadronElectoral.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPadronElectoral.setBorderPainted(false);
        btnPadronElectoral.setContentAreaFilled(false);
        btnPadronElectoral.setFocusable(false);
        btnPadronElectoral.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPadronElectoral.setIconTextGap(8);
        btnPadronElectoral.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPadronElectoral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPadronElectoralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPadronElectoralMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(67, Short.MAX_VALUE)
                        .addComponent(btnImportarDatosDeArchivo)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrarElector)
                        .addGap(18, 18, 18)
                        .addComponent(btnPadronElectoral))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarElector, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportarDatosDeArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPadronElectoral, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Gestion de Candidatos");

        btnCrearListaCandidato.setBackground(new java.awt.Color(204, 204, 255));
        btnCrearListaCandidato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCrearListaCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/candidato.png"))); // NOI18N
        btnCrearListaCandidato.setText("Listas de candidatos");
        btnCrearListaCandidato.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrearListaCandidato.setBorderPainted(false);
        btnCrearListaCandidato.setContentAreaFilled(false);
        btnCrearListaCandidato.setFocusable(false);
        btnCrearListaCandidato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearListaCandidato.setIconTextGap(8);
        btnCrearListaCandidato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCrearListaCandidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearListaCandidatoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearListaCandidatoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnCrearListaCandidato)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearListaCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Gestion de Comisio");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jMenu1.setText("Configuracion de la Eleccion");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Electores");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem1.setText("Importar Electores desde archivo");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem2.setText("Alta de Elector");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem3.setText("Padron de Electores");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Candidatos de la Eleccion");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Mesas Electorales");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo que se accionara una vez que se pase el puntero sobre el boton.
     *
     * @param evt
     */
    private void btnRegistrarElectorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarElectorMouseEntered
        btnRegistrarElector.setContentAreaFilled(true);
    }//GEN-LAST:event_btnRegistrarElectorMouseEntered

    /**
     * Metodo que se accionara una vez que se quite el puntero sobre el boton.
     *
     * @param evt
     */
    private void btnRegistrarElectorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarElectorMouseExited
        btnRegistrarElector.setContentAreaFilled(false);
    }//GEN-LAST:event_btnRegistrarElectorMouseExited

    /**
     * Metodo que se accionara una vez que se pase el puntero sobre el boton.
     *
     * @param evt
     */
    private void btnImportarDatosDeArchivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportarDatosDeArchivoMouseEntered
        btnImportarDatosDeArchivo.setContentAreaFilled(true);
    }//GEN-LAST:event_btnImportarDatosDeArchivoMouseEntered

    /**
     * Metodo que se accionara una vez que se quite el puntero sobre el boton.
     *
     * @param evt
     */
    private void btnImportarDatosDeArchivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportarDatosDeArchivoMouseExited
        btnImportarDatosDeArchivo.setContentAreaFilled(false);
    }//GEN-LAST:event_btnImportarDatosDeArchivoMouseExited

    /**
     * Metodo que se accionara una vez que se pase el puntero sobre el boton.
     *
     * @param evt
     */
    private void btnPadronElectoralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPadronElectoralMouseEntered
        btnPadronElectoral.setContentAreaFilled(true);
    }//GEN-LAST:event_btnPadronElectoralMouseEntered

    /**
     * Metodo que se accionara una vez que se quite el puntero sobre el boton.
     *
     * @param evt
     */
    private void btnPadronElectoralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPadronElectoralMouseExited
        btnPadronElectoral.setContentAreaFilled(false);
    }//GEN-LAST:event_btnPadronElectoralMouseExited

     /**
     * Metodo que se accionara una vez que se pase el puntero sobre el boton.
     *
     * @param evt
     */
    private void btnCrearListaCandidatoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearListaCandidatoMouseEntered
        btnCrearListaCandidato.setContentAreaFilled(true);
    }//GEN-LAST:event_btnCrearListaCandidatoMouseEntered

    /**
     * Metodo que se accionara una vez que se quite el puntero sobre el boton.
     *
     * @param evt
     */
    private void btnCrearListaCandidatoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearListaCandidatoMouseExited
        btnCrearListaCandidato.setContentAreaFilled(false);
    }//GEN-LAST:event_btnCrearListaCandidatoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearListaCandidato;
    private javax.swing.JButton btnImportarDatosDeArchivo;
    private javax.swing.JButton btnPadronElectoral;
    private javax.swing.JButton btnRegistrarElector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
