package Modelo.Persistencia.POJO;
// Generated Dec 1, 2018 1:53:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private int codigocarrera;
     private String nombrecarrera;
     private Set estudiantes = new HashSet(0);

    public Carrera() {
    }

	
    public Carrera(int codigocarrera, String nombrecarrera) {
        this.codigocarrera = codigocarrera;
        this.nombrecarrera = nombrecarrera;
    }
    public Carrera(int codigocarrera, String nombrecarrera, Set estudiantes) {
       this.codigocarrera = codigocarrera;
       this.nombrecarrera = nombrecarrera;
       this.estudiantes = estudiantes;
    }
   
    public int getCodigocarrera() {
        return this.codigocarrera;
    }
    
    public void setCodigocarrera(int codigocarrera) {
        this.codigocarrera = codigocarrera;
    }
    public String getNombrecarrera() {
        return this.nombrecarrera;
    }
    
    public void setNombrecarrera(String nombrecarrera) {
        this.nombrecarrera = nombrecarrera;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


