package Modelo.Persistencia.POJO;
// Generated Dec 1, 2018 1:53:29 AM by Hibernate Tools 4.3.1



/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private long dni;
     private Carrera carrera;
     private String nombre;
     private String apellido;
     private String legajo;
     private int utimaIncripcion;
     private int cantMaterias;
     private String localidad;

    public Estudiante() {
    }

    public Estudiante(long dni, Carrera carrera, String nombre, String apellido, String legajo, int utimaIncripcion, int cantMaterias, String localidad) {
       this.dni = dni;
       this.carrera = carrera;
       this.nombre = nombre;
       this.apellido = apellido;
       this.legajo = legajo;
       this.utimaIncripcion = utimaIncripcion;
       this.cantMaterias = cantMaterias;
       this.localidad = localidad;
    }
   
    public long getDni() {
        return this.dni;
    }
    
    public void setDni(long dni) {
        this.dni = dni;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(String legajo) {
        this.legajo = legajo;
    }
    public int getUtimaIncripcion() {
        return this.utimaIncripcion;
    }
    
    public void setUtimaIncripcion(int utimaIncripcion) {
        this.utimaIncripcion = utimaIncripcion;
    }
    public int getCantMaterias() {
        return this.cantMaterias;
    }
    
    public void setCantMaterias(int cantMaterias) {
        this.cantMaterias = cantMaterias;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }




}


